Freught1/Freight/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Freught1.Controllers
{
    public class CalculatorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Freught1/Freight/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Freught1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Freught1/Freight/Controllers/UploadRateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Freught1.Controllers
{
    public class UploadRateController : Controller
    {
        // GET: UploadRate
        public ActionResult Index()
        {
            return View();
        }
    }
}

Freught1/Freight/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Freught1/Freight/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link href="~/Style/login.css" rel="stylesheet" />
<div class="wrapper fadeInDown">
    <div id="formContent">
        <div class="fadeIn first" style="margin-top:30px">
            <img src="https://ebiz5-staging.mentormedia.com/RFID-WIREFRAME/_nuxt/img/logo.9b9a022.png" id="icon" alt="User Icon" />
        </div>
        <hr role="separator" aria-orientation="horizontal" class="my-8 v-divider theme--light">
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Email </label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email" style="margin-left:35px;max-width:380px">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                @*<input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">*@
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" style="margin-left: 35px; max-width: 380px">
            </div>
            <div class="form-group form-check">
                @*<input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>*@
            </div>
            @*<button id="submitButton" type="submit" class="btn btn-primary" style="width: 17%; margin-top: 15px;">*@
            @Html.ActionLink("Submit", "Index", "Calculator", null, new { @class = "submit" })
            @*</button>*@
        </form>
        @*<form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" style="">
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <input type="submit" class="fadeIn fourth" value="Log In">
            </form>*@
        <div id="formFooter" style="margin-top:20px">

        </div>

    </div>
</div>
<script>
    $("#submitButton").click(function () {
        window.location.href = "/About";
    })
</script>
@*<h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>*@

Freught1/Freight/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mentor Media</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Style/sidebar.css" rel="stylesheet" />
    <link href="~/Style/navbar.css" rel="stylesheet" />

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="row">
        <div class="col-2">
            @RenderSection("sidebar", required: false)
        </div>
        <div class="col-10" style="font-size: 1.5rem; margin-top: 5%; justify-content: center; width: 1600px">
            @RenderBody()
        </div>
    </div>

    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Freught1/Freight/Views/UploadRate/Index.cshtml
<style>
    h3 {
        font-family: Roboto,sans-serif;
        font-size: 20px;
    }
</style>

@Html.Partial("~/Views/_Header.cshtml")
@section sidebar{
    <div class="nav-side-menu">
        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

        <div class="menu-list">

            <ul id="menu-content" class="menu-content collapse out">
                <a href="/Calculator/Index" style="text-decoration:none">
                    <li data-toggle="collapse" data-target="#products" class="collapsed">
                        <i class="fa fa-dashboard fa-lg" style="padding-right:10px"></i>
                        Calculator
                    </li>

                </a>
                <a href="/UploadRate/Index" style="text-decoration:none">
                    <li data-toggle="collapse" data-target="#new" class="collapsed active">
                        <i class="fa fa-car fa-lg" style="padding-right:8px"></i>
                        Upload rate
                    </li>
                </a>
            </ul>
        </div>
    </div>
}
<body>
    <div style="min-height:80vH">
        <section>
            <div style=" font-size:1.5rem">
                <h3>Upload Rate</h3>
                <div class="row" style="margin-left:0px">
                    <input type="file" name="file" id="file" />
                    <br />
                    @*<input type="submit" value="Upload Image" id="upload" />*@
                    <div style="display:block">
                        <button type="button" class="btn btn-primary btn-lg" id="upload">Submit</button>
                    </div>
                </div>
            </div>
        </section>
        <footer style=" position:absolute;top:100%; font-size:15px;">
            <label style="font-weight: normal">Copyright Mentor Media, 2020</label>
        </footer>
    </div>
</body>

<script>
    $("#upload").click(function () {
        console.log("hello")
        var file = $("#file").val();
        console.log("file:", file)
        $('<tr id="tr-id">')

        if (file != "")
            alert("Import file sucessful")
        //for (i = 1; i < 15; i++) {
        //    //var cost = data[i].Cost * parseFloat(weightSelect);
        //    var cost = i * 1.5 + 20;
        //    var Australia = Number(cost).toLocaleString();
        //    var Argentina = Number(i * 1.7 + 20).toLocaleString()
        //    var Austria = Number(i * 1.9 + 20).toLocaleString()
        //    var Belgium = Number(i * 2.1 + 20).toLocaleString()
        //    var Bolivia = Number(i * 2.3 + 20).toLocaleString()
        //    var Brazil = Number(i * 2.1 + 20).toLocaleString()
        //    var Canada = Number(i * 2 + 20).toLocaleString()
        //    var Chile = Number(i * 1.9 + 20).toLocaleString()
        //    var package = Number(i).toLocaleString();
        //    console.log(cost)
        //    $('<tr id="tr-id">')
        //        .append($('<td>').append(package))
        //        .append($('<td>').append(Argentina))
        //        .append($('<td>').append(Australia))
        //        .append($('<td>').append(Austria))
        //        .append($('<td>').append(Belgium))
        //        .append($('<td>').append(Bolivia))
        //        .append($('<td>').append(Brazil))
        //        .append($('<td>').append(Canada))
        //        .append($('<td>').append(Chile))
        //        .appendTo('table');
        //}
        else {
            alert("You have not imported the file ")
        }
    })


    $("#weightSelect").change(function () {
        console.log("sadsadaf")
        var source = $("#weightSelect").val();
        console.log(source)
        var contentToRemove = document.querySelectorAll("#tr-id");
        $(contentToRemove).remove();
        if (source == "") {
            for (i = 1; i < 15; i++) {
                //var cost = data[i].Cost * parseFloat(weightSelect);
                var cost = i * 1.5 + 20;
                var Australia = Number(cost).toLocaleString();
                var Argentina = Number(i * 1.7 + 20).toLocaleString()
                var Austria = Number(i * 1.9 + 20).toLocaleString()
                var Belgium = Number(i * 2.1 + 20).toLocaleString()
                var Bolivia = Number(i * 2.3 + 20).toLocaleString()
                var Brazil = Number(i * 2.1 + 20).toLocaleString()
                var Canada = Number(i * 2 + 20).toLocaleString()
                var Chile = Number(i * 1.9 + 20).toLocaleString()
                var package = Number(i).toLocaleString();
                console.log(cost)
                $('<tr id="tr-id">')
                    .append($('<td>').append(package))
                    .append($('<td>').append(Argentina))
                    .append($('<td>').append(Australia))
                    .append($('<td>').append(Austria))
                    .append($('<td>').append(Belgium))
                    .append($('<td>').append(Bolivia))
                    .append($('<td>').append(Brazil))
                    .append($('<td>').append(Canada))
                    .append($('<td>').append(Chile))
                    .appendTo('table tbody');
            }
        }
        else {
            var cost = source * 1.5 + 20;
            var Australia = Number(cost).toLocaleString();
            var Argentina = Number(source * 1.7 + 20).toLocaleString()
            var Austria = Number(source * 1.9 + 20).toLocaleString()
            var Belgium = Number(source * 2.1 + 20).toLocaleString()
            var Bolivia = Number(source * 2.3 + 20).toLocaleString()
            var Brazil = Number(source * 2.1 + 20).toLocaleString()
            var Canada = Number(source * 2 + 20).toLocaleString()
            var Chile = Number(source * 1.9 + 20).toLocaleString()
            var package = Number(source).toLocaleString();
            console.log(cost)
            $('<tr id="tr-id">')
                .append($('<td>').append(package))
                .append($('<td>').append(Argentina))
                .append($('<td>').append(Australia))
                .append($('<td>').append(Austria))
                .append($('<td>').append(Belgium))
                .append($('<td>').append(Bolivia))
                .append($('<td>').append(Brazil))
                .append($('<td>').append(Canada))
                .append($('<td>').append(Chile))
                .appendTo('table tbody');
        }
    })
</script>

Freught1/Freight/Views/_Header.cshtml
<nav>
    <input id="nav-toggle" type="checkbox">
    <div class="logo" >
        <a href="/Calculator/Index">
            <img src="https://ebiz5-staging.mentormedia.com/RFID-WIREFRAME/_nuxt/img/logo.9b9a022.png"
                 id="icon" alt="User Icon" style="height: 65px; margin-left:-30px" />
        </a>
       
    </div>
    <div class="links">

        <button type="button" class="btn btn-danger btn-lg" style="margin-left:100%" onclick="location.href='@Url.Action("Index", "Home")'">Logout</button>

    </div>
    <label for="nav-toggle" class="icon-burger">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </label>
</nav>